// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID      string    `json:"id"`
	Content string    `json:"content"`
	UserID  string    `json:"userID"`
	User    *User     `json:"user"`
	Date    time.Time `json:"Date"`
	PostID  string    `json:"postID"`
	Post    *Post     `json:"post"`
}

type Mutation struct {
}

type NewComment struct {
	Content string `json:"content"`
	UserID  string `json:"userID"`
	PostID  string `json:"postID"`
}

type NewPost struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	Commenting bool   `json:"commenting"`
	UserID     string `json:"userID"`
}

type NewUser struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Post struct {
	ID         string     `json:"id"`
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	Date       time.Time  `json:"date"`
	Commenting bool       `json:"commenting"`
	UserID     string     `json:"userID"`
	User       *User      `json:"user"`
	Comments   []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
